feature:
 - head-branch: ['^feature', 'feature', '^feat', 'feat']

fix:
  - head-branch: ['^fix', 'fix', '^bugfix', 'bugfix']

chore:
  - head-branch: ['^chore', 'chore']

cargo-bump:
  - head-branch: ['^chore/update-version', 'chore/update-version']