name-template: 'v$RESOLVED_VERSION 🍿'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
template: |
  ## Changes

  $CHANGES

  ## Docker Tags
  ${{ env.DOCKER_METADATA_OUTPUT_TAGS }}

categories:
  - title: '🚀 Features'
    label: feature
  - title: '🐛 Bug Fixes'
    label: bugfix
  - title: '🧹 Chores'
    collapse-after: 2
    label: chore

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

autolabeler:
  - label: 'chore'
    branch:
      - '/chore\/.+/'
  - label: 'fix'
    branch:
      - '/fix\/.+/'
  - label: 'feature'
    branch:
      - '/feature\/.+/'
