name: Rust build
description: 'Builds the Rust project'

inputs:
  build-flags:
    description: 'Flags to pass to the `cargo build` command'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: rustup update && rustup component add rustfmt clippy
      shell: bash

    - name: Cache Cargo registry and build output
      uses: Swatinem/rust-cache@v2
      with:
        cache-targets: true
        cache-on-failure: true
        save-if: "${{ github.ref == 'refs/heads/master' || github.event_name == 'pull_request' }}"

    - name: Build Rust project
      run: |
        cargo build ${{ inputs.build-flags }}
        mkdir -p bin/x86_64-unknown-linux-gnu
        cp target/release/replex bin/x86_64-unknown-linux-gnu/
      shell: bash
