name: 'Set Docker Platform'
description: 'Generates a comma separated list of Docker platforms to build for.'
inputs:
  platform:
    description: 'Comma-separated list of platforms to build for.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set docker platforms
      id: set-docker
      uses: actions/github-script@v7
      with:
        result-encoding: string
        script: |
          const platforms = "${{ inputs.platform }}".split(",").map(platform => platform.trim())
          const dockerMap = {
            "x86_64 Linux": "linux/amd64",
            "ARM64 Linux": "linux/arm64",
            "x86_64 macOS": "darwin/amd64",
          }

          const docker = platforms
            .map(platform => dockerMap[platform])
            .filter(platform => platform)

          return docker.join(",")
outputs:
  platform:
    description: 'Comma-separated list of Docker platforms to build for.'
    value: ${{ steps.set-docker.outputs.result }}
