name: 'Set Build Matrix'
description: 'Generates a build matrix for the provided platforms and build types.'
inputs:
  platform:
    description: 'Comma-separated list of platforms to build for.'
    required: true
  release:
    description: 'Whether to build for release or not.'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Set matrix
      id: set-matrix
      uses: actions/github-script@v7
      with:
        result-encoding: 'string'
        script: |
          const platforms = "${{ inputs.platform }}".split(",").map(platform => platform.trim())
          const profile = "${{ inputs.release == 'true' && 'release' || 'debug' }}"

          const platformMap = {
            "linux/amd64": {
              build: "linux/amd64",
              os: "ubuntu-latest",
              target: "x86_64-unknown-linux-gnu",
              input: `target/x86_64-unknown-linux-gnu/${profile}/replex`,
              output: "bin/x86_64-unknown-linux-gnu/replex",
            },
            "linux/arm64": {
              build: "linux/arm64",
              os: "ubuntu-latest",
              target: "aarch64-unknown-linux-gnu",
              input: `target/aarch64-unknown-linux-gnu/${profile}/replex`,
              output: "bin/aarch64-unknown-linux-gnu/replex",
            },
            "darwin/amd64": {
              build: "darwin/amd64",
              os: "macOS-latest",
              target: "x86_64-apple-darwin",
              input: `target/x86_64-apple-darwin/${profile}/replex`,
              output: "bin/x86_64-apple-darwin/replex",
            },
            "darwin/arm64": {
              build: "darwin/arm64",
              os: "macos-latest",
              target: "aarch64-apple-darwin",
              input: `target/aarch64-apple-darwin/${profile}/replex`,
              output: "bin/aarch64-apple-darwin/replex",
            },
            "windows/amd64": {
              build: "windows/amd64",
              os: "ubuntu-latest",
              target: "x86_64-pc-windows-gnu",
              input: `target/x86_64-pc-windows-gnu/${profile}/replex`,
              output: "bin/x86_64-pc-windows-gnu/replex.exe",
            },
          }

          const matrix = platforms
            .map(platform => platformMap[platform])
            .filter(platform => platform)

          return JSON.stringify(matrix)
outputs:
  result:
    description: 'JSON string containing the matrix configuration for builds.'
    value: ${{ steps.set-matrix.outputs.result }}
