[package]
name = "replex-deps"
version = "1.0.0"
edition = "2021"

[dependencies]
bincode = { version = "2.0.0-rc.3", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
strum = "0.24.1"
strum_macros = "0.24.3"
yaserde = "0.12.0"
yaserde_derive = "0.12.0"
