[package]
name = "replex-common"
version = "1.0.11"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.36"
serde = { version = "1.0", features = ["derive"] }
strum_macros = "0.26.2"
syn = { version = "1.0", features = ["full"] }
