name: 'Decide build platform'
description: 'Decides which platforms to build for.'
inputs:
  platform:
    description: 'Comma-separated list of platforms to build for.'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Set platform
      id: set-platform
      uses: actions/github-script@v7
      with:
        result-encoding: 'string'
        script: |
          const eventName = "${{ github.event_name }}";
          const ref = "${{ github.ref }}";
          const input = "${{ github.event.inputs.platform }}";
          
          const platformMap = {
            all: "linux/amd64, linux/arm64, darwin/amd64, darwin/arm64, windows/amd64",
            linux: "linux/amd64, linux/arm64",
            macos: "darwin/amd64, darwin/arm64",
            windows: "windows/amd64",
          };
          
          if (ref.startsWith('refs/tags/v')) {
            return platformMap['all'];
          }

          if (userInput && eventName === 'workflow_dispatch') {
            return platformMap[input];
          }

          if (userInput && eventName === 'workflow_call') {
            return platformMap[input];
          }
          
          return platformMap['linux'];
outputs:
  result:
    description: 'Comma-separated list of platforms to build for.'
    value: ${{ steps.set-platform.outputs.result }}
