name: Scheduled Label Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,12 * * *'

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    name: Label PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.REPLEX_PAT }}
