name: Manual Docker build and push

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build-rust.yml
    secrets: inherit
    with:
      platform: 'linux/amd64, linux/arm64'
      release: false
      upload_url: ${{ needs.prepare.outputs.upload_url }}

  docker:
    name: Docker
    if: ${{ github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' }}
    needs: [build]
    uses: ./.github/workflows/build-docker.yml
    secrets: inherit
    with:
      platform: 'linux/amd64, linux/arm64'
      version: ${{ needs.prepare.outputs.next_version }}
    